services:
  jenkins:
    build: ./data/jenkins_dind
    container_name: jenkins
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    restart: always
    volumes:
      - ./mounted/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"] # Adjust URL if needed
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
  nexus:
    image: sonatype/nexus3:3.84.0-alpine
    container_name: nexus
    ports:
      - "8888:8081"  # Nexus UI/API port
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2048m -XX:MaxDirectMemorySize=2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status/writable"] # Adjust URL if needed
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
  allure-service:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: "NONE"   # CI push mode
      KEEP_HISTORY: "1"
      KEEP_HISTORY_LATEST: "50"
      SECURITY_ENABLED: "1"
      SECURITY_USER: admin
      SECURITY_PASS: admin
    ports: ["5050:5050"]
    volumes:
      - ./data/projects:/app/projects
  allure-ui:
    image: frankescobar/allure-docker-service-ui:latest
    container_name: allure-ui
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
    ports: 
      - "5252:5252"
    depends_on: 
      - allure-service
volumes:
  nexus-data: